/** Türkçe–İngilizce kelime çiftleri (kelime eşleştirme oyunu). */
export const WORD_PAIRS = [
  { tr: "elma", en: "apple" },
  { tr: "kitap", en: "book" },
  { tr: "su", en: "water" },
  { tr: "ev", en: "house" },
  { tr: "araba", en: "car" },
  { tr: "güneş", en: "sun" },
  { tr: "ay", en: "moon" },
  { tr: "ağaç", en: "tree" },
  { tr: "kuş", en: "bird" },
  { tr: "balık", en: "fish" },
  { tr: "köpek", en: "dog" },
  { tr: "kedi", en: "cat" },
  { tr: "kapı", en: "door" },
  { tr: "pencere", en: "window" },
  { tr: "masa", en: "table" },
  { tr: "sandalye", en: "chair" },
  { tr: "yatak", en: "bed" },
  { tr: "anne", en: "mother" },
  { tr: "baba", en: "father" },
  { tr: "kardeş", en: "sibling" },
  { tr: "arkadaş", en: "friend" },
  { tr: "öğretmen", en: "teacher" },
  { tr: "öğrenci", en: "student" },
  { tr: "okul", en: "school" },
  { tr: "ders", en: "lesson" },
  { tr: "soru", en: "question" },
  { tr: "cevap", en: "answer" },
  { tr: "kalem", en: "pen" },
  { tr: "kağıt", en: "paper" },
  { tr: "telefon", en: "phone" },
  { tr: "bilgisayar", en: "computer" },
  { tr: "internet", en: "internet" },
  { tr: "müzik", en: "music" },
  { tr: "şarkı", en: "song" },
  { tr: "film", en: "movie" },
  { tr: "oyun", en: "game" },
  { tr: "spor", en: "sport" },
  { tr: "yemek", en: "food" },
  { tr: "kahvaltı", en: "breakfast" },
  { tr: "öğle yemeği", en: "lunch" },
  { tr: "akşam yemeği", en: "dinner" },
  { tr: "ekmek", en: "bread" },
  { tr: "süt", en: "milk" },
  { tr: "çay", en: "tea" },
  { tr: "kahve", en: "coffee" },
  { tr: "şehir", en: "city" },
  { tr: "köy", en: "village" },
  { tr: "ülke", en: "country" },
  { tr: "deniz", en: "sea" },
  { tr: "nehir", en: "river" },
  { tr: "dağ", en: "mountain" },
  { tr: "orman", en: "forest" },
  { tr: "çiçek", en: "flower" },
  { tr: "renk", en: "color" },
  { tr: "kırmızı", en: "red" },
  { tr: "mavi", en: "blue" },
  { tr: "yeşil", en: "green" },
  { tr: "sarı", en: "yellow" },
  { tr: "siyah", en: "black" },
  { tr: "beyaz", en: "white" },
  { tr: "sıcak", en: "hot" },
  { tr: "soğuk", en: "cold" },
  { tr: "büyük", en: "big" },
  { tr: "küçük", en: "small" },
  { tr: "iyi", en: "good" },
  { tr: "kötü", en: "bad" },
  { tr: "yeni", en: "new" },
  { tr: "eski", en: "old" },
  { tr: "hızlı", en: "fast" },
  { tr: "yavaş", en: "slow" },
  { tr: "kolay", en: "easy" },
  { tr: "zor", en: "difficult" },
  { tr: "mutlu", en: "happy" },
  { tr: "üzgün", en: "sad" },
  { tr: "yorgun", en: "tired" },
  { tr: "aç", en: "hungry" },
  { tr: "susamış", en: "thirsty" },
  { tr: "bugün", en: "today" },
  { tr: "yarın", en: "tomorrow" },
  { tr: "dün", en: "yesterday" },
  { tr: "sabah", en: "morning" },
  { tr: "akşam", en: "evening" },
  { tr: "gece", en: "night" },
  { tr: "hafta", en: "week" },
  { tr: "ay (takvim)", en: "month" },
  { tr: "yıl", en: "year" },
  { tr: "pazartesi", en: "Monday" },
  { tr: "cuma", en: "Friday" },
  { tr: "hafta sonu", en: "weekend" },
  { tr: "bir", en: "one" },
  { tr: "iki", en: "two" },
  { tr: "üç", en: "three" },
  { tr: "dört", en: "four" },
  { tr: "beş", en: "five" },
  { tr: "on", en: "ten" },
  { tr: "yüz", en: "hundred" },
  { tr: "el", en: "hand" },
  { tr: "ayak", en: "foot" },
  { tr: "göz", en: "eye" },
  { tr: "kulak", en: "ear" },
  { tr: "burun", en: "nose" },
  { tr: "ağız", en: "mouth" },
  { tr: "diş", en: "tooth" },
  { tr: "saç", en: "hair" },
  { tr: "kalp", en: "heart" },
  { tr: "baş", en: "head" },
  { tr: "kol", en: "arm" },
  { tr: "bacak", en: "leg" },
  { tr: "gökyüzü", en: "sky" },
  { tr: "bulut", en: "cloud" },
  { tr: "yağmur", en: "rain" },
  { tr: "kar", en: "snow" },
  { tr: "rüzgar", en: "wind" },
  { tr: "hava", en: "weather" },
  { tr: "iş", en: "work" },
  { tr: "para", en: "money" },
  { tr: "zaman", en: "time" },
  { tr: "yer", en: "place" },
  { tr: "yol", en: "road" },
  { tr: "istasyon", en: "station" },
  { tr: "uçak", en: "plane" },
  { tr: "tren", en: "train" },
  { tr: "otobüs", en: "bus" },
  { tr: "bisiklet", en: "bicycle" },
  { tr: "yürümek", en: "to walk" },
  { tr: "koşmak", en: "to run" },
  { tr: "uyumak", en: "to sleep" },
  { tr: "yemek (fiil)", en: "to eat" },
  { tr: "içmek", en: "to drink" },
  { tr: "okumak", en: "to read" },
  { tr: "yazmak", en: "to write" },
  { tr: "konuşmak", en: "to speak" },
  { tr: "dinlemek", en: "to listen" },
  { tr: "görmek", en: "to see" },
  { tr: "bilmek", en: "to know" },
  { tr: "istemek", en: "to want" },
  { tr: "sevmek", en: "to love" },
  { tr: "yardım", en: "help" },
  { tr: "sorun", en: "problem" },
  { tr: "fikir", en: "idea" },
  { tr: "hayat", en: "life" },
  { tr: "dünya", en: "world" },
] as const;

export type WordPair = (typeof WORD_PAIRS)[number];
